apiVersion: v1
kind: PersistentVolume
metadata:
  name: learn-pv
spec:
  storageClassName: local-storage-learn
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  hostPath:
    path: /run/desktop/mnt/host/c
    type: Directory
