apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: local-storage-mongo
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  hostPath:
    path: /mnt/c/Moneytech/mongo-vol
    type: Directory
